apiVersion: v1
kind: PersistentVolume
metadata:
  name: pp-api-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: "/mnt/data/postgres"