apiVersion: v1
kind: Service
metadata:
  name: pp-api
spec:
  selector:
    app: pp-api
  type: ClusterIP
  ports:
    - port: 
        valueFrom:
          configMapKeyRef:
            name: pp-api-config
            key: api_port      
      targetPort: 8080