apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: pp-api
  template:
    metadata:
      labels:
        app: pp-api
    spec:
      containers:
        - name: pp-api
          # image: {{ .Values.api.image }}
          image: pp-api
          # imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "400m"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pp-api-db-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-api-db-secrets
                  key: db_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pp-api-db-config
                  key: db_name
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pp-api-db-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pp-api-db-config
                  key: db_port
            

