apiVersion: v2
name: pp
description: Fitness challenge tracker app helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.12.0 
    repository: https://kubernetes.github.io/ingress-nginx