pullImages: true
githubPackageRegistryToken: ""

ingress:
  applicationHost: pp-dev.passed-pawn.com
  caSignedCertificateName: letsencrypt-prod

ingress-nginx:
  controller:
    service:
      externalIPs:
        - 51.38.43.104

api:
  replicaCount: 1
  image: ghcr.io/passed-pawn-dev/pp-backend/pp-api:latest
  db:
    replicaCount: 1
    name: passedpawn
    username: ""
    password: ""
    host: pp-api-db
  appSettings: ""

frontend:
  replicaCount: 1
  image: ghcr.io/passed-pawn-dev/pp-frontend/pp-frontend:latest

aiApi:
  replicaCount: 1
  image: ghcr.io/passed-pawn-dev/pp-ai/pp-ai-api:latest
  mistralApiKey: ""

keycloak:
  image: quay.io/keycloak/keycloak:26.0.5
  replicaCount: 1
  adminUsername: ""
  adminPassword: ""
  db:
    replicaCount: 1
    vendor: postgres
    host: pp-keycloak-db
    name: pp-keycloak
    port: 5432
    username: ""
    password: ""
  host: auth-dev.passed-pawn.com
  adminHost: localhost:8080