pullImages: false
githubPackageRegistryToken: ""
  
ingress:
  applicationHost: pp-local.passed-pawn.com
  keycloakHost: auth-local.passed-pawn.com

api:
  replicaCount: 1
  image: pp-api
  imagePullPolicy: ""
  db:
    replicaCount: 1
    name: passedpawn
    username: ""
    password: ""
    host: pp-api-db

frontend:
  replicaCount: 1
  image: pp-frontend

keycloak:
  image: quay.io/keycloak/keycloak:26.0.5
  replicaCount: 1
  adminUsername: ""
  adminPassword: ""
  db:
    replicaCount: 1
    vendor: postgres
    host: pp-keycloak-db
    name: pp-keycloak
    port: 5432
    username: ""
    password: ""
