apiVersion: v1
kind: Secret
metadata:
  name: pp-api-db-secrets
type: Opaque
data:
  db_username: {{ required "api.db.username is required" .Values.api.db.username | b64enc }}
  db_password: {{ required "api.db.password is required" .Values.api.db.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-keycloak-secrets
type: Opaque
data:
  admin_username: {{ required "keycloak.adminUsername is required" .Values.keycloak.adminUsername | b64enc }}
  admin_password: {{ required "keycloak.adminPassword is required" .Values.keycloak.adminPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-keycloak-db-secrets
type: Opaque
data:
  db_username: {{ required "keycloak.db.username is required" .Values.keycloak.db.username | b64enc }}
  db_password: {{ required "keycloak.db.password is required" .Values.keycloak.db.password | b64enc }}
---
{{ if .Values.pullImages }}
apiVersion: v1
kind: Secret
metadata:
  name: pp-github-package-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "keycloak.db.username is required" .Values.keycloak.db.username | b64enc }}
{{ end }}