apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pp-ingress
  labels:
    app.kubernetes.io/name: pp
    app.kubernetes.io/version: 1.0.0
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | default "passed-pawn" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: pp-api
                port: 
                  number: 8080