apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pp-ingress
  labels:
    app.kubernetes.io/name: pp
    app.kubernetes.io/version: 1.0.0
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.controller.ingressClassResource.name | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | default "fitness-challenge-tracker" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pp-api
                port:
              valueFrom:
                configMapKeyRef:
                  name: pp-api-config
                  key: api_port
