apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pp-ingress
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    cert-manager.io/issuer: "selfsigned-issuer"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - {{ .Values.ingress.applicationHost }}
  #   secretName: example-tls
  rules:
    - host: {{ .Values.ingress.applicationHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pp-frontend
                port: 
                  number: 80
    - host: {{ .Values.ingress.applicationHost }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pp-api
                port: 
                  number: 8080
    - host: {{ .Values.ingress.keycloakHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pp-keycloak
                port: 
                  number: 8080