apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pp-ingress
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    {{ if .Values.ingress.caSignedCertificateName }}
    cert-manager.io/issuer: {{ .Values.ingress.caSignedCertificateName }}
    {{ end }}
spec:
  ingressClassName: nginx
  {{ if .Values.ingress.caSignedCertificateName }}
  tls:
  - hosts:
    - {{ .Values.ingress.applicationHost }}
    - {{ .Values.keycloak.host }}
    secretName: passed-pawn-tls
  {{ end }}
  rules:
    - host: {{ .Values.ingress.applicationHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pp-frontend
                port: 
                  number: 80
    - host: {{ .Values.ingress.applicationHost }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pp-api
                port: 
                  number: 8080
    - host: {{ .Values.ingress.applicationHost }}
      http:
        paths:
          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: pp-ai-api
                port: 
                  number: 8000                 
    - host: {{ .Values.keycloak.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pp-keycloak
                port: 
                  number: 8080