apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp-keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: pp-keycloak
  template:
    metadata:
      labels:
        app: pp-keycloak
    spec:
    {{ if .Values.pullImages }}
      imagePullSecrets:
        - name: pp-github-package-registry-key
    {{ end }}    
      containers:
        - name: pp-keycloak
          image: {{ .Values.keycloak.image }}
          args: ["--verbose", "start", '--optimized']
          ports:
          - containerPort: 8080
            name: http
          env:
            - name: KC_PROXY
              value: "edge"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-secrets
                  key: admin_username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-secrets
                  key: admin_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-db-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-db-secrets
                  key: db_password
            - name: DB_VENDOR
              value: {{ .Values.keycloak.db.vendor }}
            - name: DB_ADDR
              value: {{ .Values.keycloak.db.host }}
            - name: DB_DATABASE
              value: {{ .Values.keycloak.db.name }}
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: DB_PORT
              value: "{{ .Values.keycloak.db.port }}"
            - name: KC_HOSTNAME
              value: "https://{{ .Values.keycloak.host }}"
            - name: KC_HOSTNAME_ADMIN
              value: "http://{{ .Values.keycloak.adminHost }}"
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: "true"