{{ if .Values.manualPvsEnabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pp-keycloak-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: "/mnt/data/postgres"
{{ end }}