apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pp-keycloak-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.manualPvsEnabled}}
  storageClassName: manual
  {{ else }}
  storageClassName: longhorn-crypto-global
  {{ end }}
  resources:
    requests:
      storage: 1Gi
