apiVersion: v1
kind: Service
metadata:
  name: pp-keycloak
spec:
  selector:
    app: pp-keycloak
  type: ClusterIP
  ports:
    - port: 
        valueFrom:
          configMapKeyRef:
            name: pp-keycloak-config
            key: keycloak_port      
      targetPort: 8080
