apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp-keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: pp-keycloak
  template:
    metadata:
      labels:
        app: pp-keycloak
    spec:
      containers:
        - name: pp-keycloak
          image: {{ .Values.keycloak.image }}
          args: ["start-dev", "--import-realm"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-secrets
                  key: admin_username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-secrets
                  key: admin_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-db-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-db-secrets
                  key: db_password
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: pp-keycloak-db-config
                  key: db_vendor
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: pp-keycloak-db-config
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: pp-keycloak-db-config
                  key: db_name
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pp-keycloak-db-config
                  key: db_port
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import  # This is where Keycloak looks for realm files
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-realm-config  # The ConfigMap storing your realm JSON          