apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pp-keycloak-db
spec:
  replicas: {{ .Values.keycloak-db.replicaCount }}
  serviceName: pp-keycloak-db
  selector:
    matchLabels:
      app: pp-keycloak-db
  template:
    metadata:
      labels:
        app: pp-keycloak-db
    spec:
      containers:
        - name: pp-keycloak-db
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-db-secrets
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-keycloak-db-secrets
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pp-keycloak-db-config
                  key: db_name
            # - name: POSTGRES_HOST_AUTH_METHOD
            #   # this is not a secret, but a flag
            #   value: password            
          ports:
            - containerPort: 5432
