## TODO - make more restrictive rbac: jenkins accesses only app namespace

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins
roleRef:
  kind: ClusterRole
  name: cluster-admin
