apiVersion: v1
kind: Secret
metadata:
  name: pp-dev-ops-ssh
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:toKrzysztof/passed-pawn-dev-ops"
stringData:
  privateKey: {{ required "secrets.ppDevOpsSshPrivateKey is required" .Values.secrets.ppDevOpsSshPrivateKey | b64enc }}
  username: toKrzysztof
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-frontend-ssh
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:toKrzysztof/passed-pawn-frontend"
stringData:
  privateKey: {{ required "secrets.ppFrontendSshPrivateKey is required" .Values.secrets.ppFrontendSshPrivateKey | b64enc }}
  username: toKrzysztof
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-backend-ssh
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:toKrzysztof/passed-pawn-backend"
stringData:
  privateKey: {{ required "secrets.ppBackendSshPrivateKey is required" .Values.secrets.ppBackendSshPrivateKey | b64enc }}
  username: toKrzysztof
