apiVersion: v1
kind: Secret
metadata:
  name: pp-dev-ops-ssh
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:passed-pawn-dev/pp-dev-ops"
stringData:
  username: toKrzysztof
  passphrase: {{ required "secrets.ppDevOps.sshPrivateKey is required" .Values.secrets.ppDevOps.passphrase }}
  privateKey: |-
{{ required "secrets.ppDevOps.sshPrivateKey is required" .Values.secrets.ppDevOps.sshPrivateKey | trim | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-frontend-ssh
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:passed-pawn-dev/pp-frontend"
stringData:
  username: toKrzysztof
  passphrase: {{ required "secrets.ppFrontend.sshPrivateKey is required" .Values.secrets.ppFrontend.passphrase }}
  privateKey: |-
{{ required "secrets.ppFrontend.sshPrivateKey is required" .Values.secrets.ppFrontend.sshPrivateKey | trim | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-backend-ssh
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:passed-pawn-dev/pp-backend"
stringData:
  username: toKrzysztof
  passphrase: {{ required "secrets.ppBackend.sshPrivateKey is required" .Values.secrets.ppBackend.passphrase }}
  privateKey: |-
{{ required "secrets.ppBackend.sshPrivateKey is required" .Values.secrets.ppBackend.sshPrivateKey | trim | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-cicd-github-service-account-personal-access-token
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "push images to github package registry"
stringData:
  username: passed-pawn-cicd
  password: |-
{{ required "secrets.githubServiceAccountPersonalAccessToken is required" .Values.secrets.githubServiceAccountPersonalAccessToken | trim | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-app-chart-secrets-file
  labels:
    "jenkins.io/credentials-type": "secretFile"
  annotations:
    "jenkins.io/credentials-description" : "app chart-secrets file"
stringData:
  filename: pp-app-chart-secrets-file.yaml
data:
  data: YXBpOg0KICBkYjoNCiAgICB1c2VybmFtZTogdXNlcg0KICAgIHBhc3N3b3JkOiBwYXNzd29yZA0Ka2V5Y2xvYWs6DQogIGFkbWluVXNlcm5hbWU6IGFkbWluDQogIGFkbWluUGFzc3dvcmQ6IGFkbWluDQogIGRiOg0KICAgIHVzZXJuYW1lOiB1c2VybmFtZQ0KICAgIHBhc3N3b3JkOiBwYXNzd29yZA==