apiVersion: v2
name: platform
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: 1.17.1
    repository: https://charts.jetstack.io