apiVersion: v2
name: platform
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: 1.17.1
    alias: cert-manager
    repository: https://charts.jetstack.io
  - name: longhorn
    version: 1.8.1
    repository: https://charts.longhorn.io
    alias: longhorn
