# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: local-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 32Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv
# spec:
#   capacity:
#     storage: 32Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: /data/volumes/pv1